### ISSUE TITLE
Cursor jumping when entering iedit from expand-region

### ISSUE THREAD

**Issue by fmdkdd** [syl20bnr/evil-iedit-state#2]
When entering iedit-state from expand-region (SPC v e in Spacemacs), the cursor goes down and left.

Trying with a vanilla Spacemacs configuration, there appears to be a conflict with the way I've remapped HJKL to JKHL and this [particular line](https://github.com/syl20bnr/evil-iedit-state/blob/master/evil-iedit-state.el#L161) in evil-iedit-state.el. 

As I understand, this line sends the key sequence "kj" as a workaround to exit the overlay map of expand-region.  Since "kj" is up/down in the default bindings, the cursor ends up not moving (or fast enough for the user to notice).  In my setup, "kj" is down/left, which explains the cursor move.

I need to remap HJKL because I'm using a Colemak keyboard layout.

Changing "kj" to "hk" in evil-iedit-state.el is a temporary workaround for me, but maybe there is a cleaner way to exit the overlay?

**Comment by syl20bnr** [comment]
Fixed, thanks again :-)
