### ISSUE TITLE
Rename iedit-toggle-unmatched-lines-visible to iedit-show/hide-unmatched-lines

### ISSUE THREAD

**Issue by sgepigon** [syl20bnr/evil-iedit-state#20]
iedit renamed iedit-toggle-unmatched-lines-visible to iedit-show/hide-unmatched-lines upstream in victorhge/iedit@745ea6f

Raised an issue in https://github.com/syl20bnr/spacemacs/issues/9690 and opened a pull request in https://github.com/syl20bnr/evil-iedit-state/pull/19 but posting an issue here to officially "report upstream." (as suggested in https://github.com/syl20bnr/spacemacs/issues/9690#event-1292502848)

**Comment by Miciah** [comment]
Should this issue have been closed when #19 was merged?

**Comment by syl20bnr** [comment]
Indeed :-)
