### ISSUE TITLE
iedit fails to exit but throws error of void function iedit-cleanup

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/evil-iedit-state#27]
To be short, I have found that the error is a result of [this commit](https://github.com/tsdh/iedit/commit/be44da7e2196895dadb28e3013ec1733d853cd97). So the iedit-cleanup was modified and renamed to iedit-lib-cleanup, but I am not sure what the modification means.

**Comment by mkleehammer** [comment]
Until it is released, some may find this useful:

```
(defalias 'iedit-cleanup 'iedit-lib-cleanup)
```

**Comment by hariseldon78** [comment]
To facilitate future searches: when trying to exit the message error reported is `Symbol's function definition is void: iedit-cleanup`

**Comment by syl20bnr** [comment]
Closed by https://github.com/syl20bnr/evil-iedit-state/pull/28, going to release v1.2
