### ISSUE TITLE
evil-redirect-digit-argument was removed

### ISSUE THREAD

**Issue by kepi** [syl20bnr/evil-iedit-state#36]
`evil-redirect-digit-argument` was [removed](https://github.com/emacs-evil/evil/commit/17c635f6e1f538bf4b2c3c276ddd9d4d165a52fb#diff-47302cddd5e39bfe2c8dcd1b006b8a2c683f070472d9bb138d20a243a3d71aa1L745) from `evil-maps.el` rendering errors when using spacemacs.

```
File mode specification error: (void-function evil-redirect-digit-argument)
```

I don't understand your code enough to provide PR, but at least this PR for evil-org-mode might be helpfull https://github.com/Somelauw/evil-org-mode/pull/95

**Comment by mkleehammer** [comment]
Can we get a new release on MELPA for this?  Thanks.
