### ISSUE TITLE
Some way to expand the current selection horizontally

### ISSUE THREAD

**Issue by expez** [syl20bnr/evil-iedit-state#6]
I'm trying to edit this several lines of this:

`[refactor-nrepl.ns.helpers <more stuff>]` 

but I can't select the entire thing, I can only pick the parts delimited by `.`.

**Comment by syl20bnr** [comment]
Does selecting the text before entering the iedit state work ?

**Comment by syl20bnr** [comment]
Using expand-region (SPC v in spacemacs) or selecting the text before entering iedit seem to work.
Closing this for now. Feel free to reopen if needed.
